- hosts: app
  become: yes
  tasks:
    - name: Update repositories cache
      shell: apt-get update
      
    - name: install jdk mysql
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
          - mysql-client-5.7
          - openjdk-8-jdk
          - python-mysqldb
      state: present
      

    - name: hosts
      template:
        src: host1
        dest: /etc/hosts
        owner: root
        mode: 0600          

    - name: Add the user 'APP_USER' with a specific uid and a primary group of 'admin'
      user:
        name: APP_USER
        password: '$1$c59eedeb$wRjf60SqXl9n.eKueNM6Z0' # 123456
        shell: /bin/bash
        comment: APP_USER
        append: yes
        create_home: yes
        #group: sudo
        state: present


    - name: Get my public IP from ipify.org
      ipify_facts:

    - name: URL to the web aplication
      debug: msg='{{ ipify_public_ip }}'


    - name: Check that user can connect to database
      mysql_db:
        login_user: 'db_user'
        login_password: '123456'
        login_host: 'db'
        login_port: '3306'
        name: 'data'
        state: present
      become_method: sudo

    - name: applic
      copy:
        src: "{{ item }}"
        dest: /home/APP_USER/app.jar
      with_fileglob:
        - target/*.jar
      become_user: APP_USER

    - name: Start APP
      shell: java -jar app.jar
      args: 
        chdir: /home/APP_USER/
        #executable: /bin/bash
      become: APP_USER
      async: 100
      poll: 0
      environment:
        DB_HOST: "{{ hostvars['db']['ansible_facts']['ansible_default_ipv4']['address'] }}"
        DB_NAME: 'data'
        DB_USER: 'db_user'
        DB_PASS: '123456'
        DB_PORT: '3306'
    
  
      

