- hosts: app
  #remote_user: vagrant
  #become_method: sudo
  become: yes
  tasks:

    - name: Update yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
        
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - git
        - docker
        - python-pip
        
    

    - name: pip 
      shell: pip install docker-compose
      state: present
    - name: add user to docker 
      shell: usermod -a -G docker ec2-user
      state: present
    - name: Restart docker
      service:
        name: docker
        state: restarted 
    - name: service copy
      copy:
        src: docker-compose@.service
        dest: /etc/systemd/system/docker-compose@.service
        mode: 0600    
    - name: copy
      copy:
        src: docker-compose.yml
        dest: /home/ec2-user/docker-compose.yml
        owner: ec2-user
        mode: 0600    
    - name: restart systemd 
      shell: systemctl daemon-reload && systemctl enable docker-compose@myservice
      
    - name: Start Compose
      service:
        name: docker-compose@myservice
        state: started       

    - name: Get my public IP from ipify.org
      ipify_facts:

    - name: URL to the web aplication
      debug: msg='{{ ipify_public_ip }}'
      
   - name: wait for 60 seconds
      wait_for: timeout=310 host={{ ipify_public_ip }} port=8080
      #delegate_to: localhost
    - name: URL
      uri:
        url: "http://{{ ipify_public_ip }}:8080/manage/health"
        return_content: yes
      register: webpage
      #change:"'UP' not in webpage.content"
    - name: Show Health
      debug: msg='{{ webpage.json.status }}'
    - name: Fail if UP is not in the page content
      fail:
        debug: 
          msg: "APP NOT UP"
      when: "'UP' not in webpage.content" 
        
    

