- hosts: app
  #remote_user: vagrant
  #become_method: sudo
  become: yes
  tasks:

    - name: Update yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
        
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - wget
        - git
        - docker
        - python-pip
        
    

    - name: pip 
      shell: pip install docker-compose
      state: present
    - name: add user to docker 
      shell: usermod -a -G docker ec2-user
      state: present
    - name: Restart docker
      service:
        name: docker
        state: restarted 
    - name: data container
      shell: docker-compose up -d

        
    

