- hosts: app
  #remote_user: vagrant
  #become_method: sudo
  become: yes
  tasks:

    - name: Update yum
      yum:
        name: '*'
        state: latest
        update_cache: yes
        
    - name: Install packages
      yum:
        name: "{{ item }}"
        state: present
        update_cache: yes
        loop:
          - wget
          - git
    - name: docker inst 
      shell: curl -sSL get.docker.com  | sh 
