version: "2"
services:
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=db
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=1234
    #ports: 3306:3306
  app:
    image: grebec/app
   # command: ping db
    ports:
      - "8080:8080"
    #volumes:
    #  - .:/code
