version: "2"
services:
  db:
    image: mysql
    environment:
      - MYSQL_USERNAME=test
    #ports: 3306:3306
  app:
    image: ubuntu
    command: ping db
    ports:
      - "5000:5000"
    #volumes:
    #  - .:/code
