- hosts: db
  #remote_user: vagrant
  #become_method: sudo
  become: yes
  tasks:
      

      # - name: V_A_R_S
    #   template:
    #     src: var.sh
    #     dest: /home/
    # - name: start vars  
    #   shell: ./var.sh
    #   args: 
    #     chdir: /home/ 
    #   become: yes 
    - name: Install DataBase
      apt: pkg={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
          - mysql-server-5.7
          - mysql-client-5.7
          - mysql-common
          - python-mysqldb

    - name: Start the MySQL service
      service: 
        name: mysql 
        state: started
        enabled: true    
    - name: Create new db
      mysql_db:
        name: data
        state: present
    
    - name: Create db user
      mysql_user:
        name: 'db_user'
        host: '192.168.%.%'
        password: '123456'
        priv: 'pc.*:ALL,GRANT/data.*:ALL,GRANT/mysql.*:ALL,GRANT'
        state: present
      become: yes
    
    - name: hosts
      template:
        src: host1
        dest: /etc/hosts
        owner: root
        mode: 0600
    
    - name: Copy .my.cnf file to root
      template:
        src: .my.cnf
        dest: /root/.my.cnf
        owner: root
        mode: 0600
        
    - name: Copy cnf file
      template:
        src: .my.cnf
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        owner: root
        mode: 0600
        
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

    - name: Check that user can connect to database
      mysql_db:
        login_user: 'root'
        login_password: '123456'
        login_host: 'db'
        login_port: '3306'
        name: 'data'
        state: present
      become_method: sudo
    

 
